version: "3.7"
 
networks:
  internal:
    external: false

services:
  sobatfillah.service:
    container_name: sobatfillah.service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile 
    restart: unless-stopped
    depends_on:
      - sobatfillah.postgres
    links: 
      - sobatfillah.postgres
    ports:
    - 8081:8081
    networks:
      - internal


  sobatfillah.postgres:
    image: postgres
    container_name: sobatfillah.postgres
    restart: always
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - ./db:/postgres
    networks:
      - internal

  sobatfillah.pgadmin:
    image: dpage/pgadmin4
    container_name: sobatfillah.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: saiful@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
    links:
      - sobatfillah.postgres
    depends_on:
     - sobatfillah.postgres
    ports:
      - "5050:80"
    networks:
      - internal
    restart: always

